import { useEffect, useState } from 'react';
import { useAuthStore } from '../../auth/authStore';
import { useGameStore } from '../../store/gameStore';
import { signOut, updateUsername } from '../../auth/authService';
import { loadMyStats, type MyStats } from '../../stats/statsService';

function fmt(n: number): string {
  return n.toLocaleString();
}

function fmtDuration(ms: number): string {
  const s = Math.floor(ms / 1000);
  const m = Math.floor(s / 60);
  return m > 0 ? `${m}m ${s % 60}s` : `${s}s`;
}

export default function AccountScreen() {
  const accountOpen = useAuthStore(s => s.accountOpen);
  const closeAll = useAuthStore(s => s.closeAll);
  const profile = useAuthStore(s => s.profile);
  const user = useAuthStore(s => s.user);
  const unlockedCharacterIds = useGameStore(s => s.unlockedCharacterIds);
  const campaignClearCount = useGameStore(s => s.campaignClearCount);

  const [editing, setEditing] = useState(false);
  const [nameInput, setNameInput] = useState('');
  const [nameError, setNameError] = useState('');
  const [nameSaving, setNameSaving] = useState(false);
  const [stats, setStats] = useState<MyStats | null>(null);

  useEffect(() => {
    if (!accountOpen || !user) return;
    loadMyStats(user.id).then(setStats);
  }, [accountOpen, user]);

  if (!accountOpen || !user || !profile) return null;

  function handleClose() {
    setEditing(false);
    setNameError('');
    closeAll();
  }

  function startEdit() {
    setNameInput(profile!.username);
    setNameError('');
    setEditing(true);
  }

  function cancelEdit() {
    setEditing(false);
    setNameError('');
  }

  async function saveUsername() {
    const trimmed = nameInput.trim();
    if (!trimmed || trimmed === profile!.username) { cancelEdit(); return; }
    setNameSaving(true);
    setNameError('');
    const err = await updateUsername(user!.id, trimmed);
    setNameSaving(false);
    if (err) { setNameError(err); return; }
    setEditing(false);
  }

  async function handleSignOut() {
    await signOut();
  }

  // Detect auto-generated username pattern: AdjectiveNoun#N
  const isAutoGenerated = /^[A-Z][a-z]+[A-Z][a-z]+#\d+$/.test(profile.username);

  return (
    <div className="modal-overlay" onPointerDown={handleClose}>
      <div className="modal-sheet" onPointerDown={e => e.stopPropagation()}>

        <div className="modal-sheet-header">
          <div className="modal-sheet-back" />
          <span className="modal-sheet-title">MY ACCOUNT</span>
          <button
            className="btn-utility header-icon-btn modal-sheet-close"
            onClick={handleClose}
            aria-label="Close"
          >
            <img src="/assets/ui/icon-close.svg" className="header-icon-img" alt="" />
          </button>
        </div>

        <div className="modal-sheet-body">

          {/* Username */}
          {editing ? (
            <>
              <div className="account-username-row">
                <input
                  className="auth-field account-edit-field"
                  type="text"
                  maxLength={20}
                  value={nameInput}
                  autoFocus
                  onChange={e => { setNameInput(e.target.value); setNameError(''); }}
                  onKeyDown={e => {
                    if (e.key === 'Enter') saveUsername();
                    if (e.key === 'Escape') cancelEdit();
                  }}
                />
                <button className="btn btn-sm" onClick={saveUsername} disabled={nameSaving}>
                  {nameSaving ? '...' : 'SAVE'}
                </button>
                <button className="btn btn-sm btn-secondary" onClick={cancelEdit}>
                  CANCEL
                </button>
              </div>
              <p className={`auth-error${nameError ? ' visible' : ''}`}>{nameError || '\u00A0'}</p>
            </>
          ) : (
            <>
              <div className="account-username-row">
                <span className="account-username">{profile.username}</span>
                <button className="btn btn-sm btn-secondary" onClick={startEdit}>
                  EDIT
                </button>
              </div>
              {isAutoGenerated && (
                <p className="account-username-nudge">
                  This is your auto-generated fighter name. Want to set your own?
                </p>
              )}
            </>
          )}

          <div className="account-divider" />

          <span className="account-section-label">Online Record</span>
          <div className="account-stat-row">
            <span>Wins / Losses</span>
            <span className="account-stat-value">
              {stats ? `${stats.onlineWins} / ${stats.onlineLosses}` : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>Win rate</span>
            <span className="account-stat-value">
              {stats ? (stats.winRate !== null ? `${stats.winRate}%` : '—') : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>Best win streak</span>
            <span className="account-stat-value">
              {stats ? (stats.bestWinStreak > 0 ? stats.bestWinStreak : '—') : '—'}
            </span>
          </div>

          <div className="account-divider" />

          <span className="account-section-label">Matches Played</span>
          <div className="account-stat-row">
            <span>Online</span>
            <span className="account-stat-value">
              {stats ? (stats.matchesOnline > 0 ? stats.matchesOnline : '—') : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>Campaign</span>
            <span className="account-stat-value">
              {stats ? (stats.matchesCampaign > 0 ? stats.matchesCampaign : '—') : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>Practice</span>
            <span className="account-stat-value">
              {stats ? (stats.matchesPractice > 0 ? stats.matchesPractice : '—') : '—'}
            </span>
          </div>

          <div className="account-divider" />

          <span className="account-section-label">Personal Bests</span>
          <div className="account-stat-row">
            <span>Highest score</span>
            <span className="account-stat-value">
              {stats ? (stats.highestScore !== null ? fmt(stats.highestScore) : '—') : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>Fastest win</span>
            <span className="account-stat-value">
              {stats ? (stats.fastestWinMs !== null ? fmtDuration(stats.fastestWinMs) : '—') : '—'}
            </span>
          </div>

          <div className="account-divider" />

          <span className="account-section-label">Progression</span>
          <div className="account-stat-row">
            <span>Fighters unlocked</span>
            <span className="account-stat-value">{unlockedCharacterIds.length}</span>
          </div>
          <div className="account-stat-row">
            <span>Campaign clears</span>
            <span className="account-stat-value">
              {campaignClearCount > 0 ? campaignClearCount : '—'}
            </span>
          </div>

          <div className="account-divider" />

          <button className="auth-signout-link" onClick={handleSignOut}>
            SIGN OUT
          </button>

        </div>
      </div>
    </div>
  );
}
