import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useAuthStore } from '../../auth/authStore';
import { useGameStore } from '../../store/gameStore';
import { signOut, updateUsername, deleteAccount } from '../../auth/authService';
import { loadMyStats, type MyStats } from '../../stats/statsService';
import { BASE_UNLOCKED } from '../../progression/progressionService';
import { useModalAnimation } from '../../hooks/useModalAnimation';
import { showToast } from '../../toasts/toastStore';

function fmt(n: number): string {
  return n.toLocaleString();
}


export default function AccountScreen() {
  const { t } = useTranslation('ui');
  const accountOpen = useAuthStore(s => s.accountOpen);
  const closeAll = useAuthStore(s => s.closeAll);
  const profile = useAuthStore(s => s.profile);
  const user = useAuthStore(s => s.user);
  const unlockedCharacterIds = useGameStore(s => s.unlockedCharacterIds);
  const campaignClearCount = useGameStore(s => s.campaignClearCount);

  const { rendered, closing } = useModalAnimation(accountOpen);

  const [confirmSignOut, setConfirmSignOut] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [deleteError, setDeleteError] = useState('');

  // Reset confirm dialogs whenever the modal closes so re-opening starts clean.
  useEffect(() => {
    if (!accountOpen) {
      setConfirmSignOut(false);
      setConfirmDelete(false);
      setDeleting(false);
      setDeleteError('');
    }
  }, [accountOpen]);
  const [editing, setEditing] = useState(false);
  const [nameInput, setNameInput] = useState('');
  const [nameError, setNameError] = useState('');
  const [nameSaving, setNameSaving] = useState(false);
  const [stats, setStats] = useState<MyStats | null>(null);

  useEffect(() => {
    if (!accountOpen || !user) return;
    setStats(null);
    loadMyStats(user.id).then(setStats);
  }, [accountOpen, user]);

  if (!rendered || !user) return null;

  function handleClose() {
    setEditing(false);
    setNameError('');
    closeAll();
  }

  function startEdit() {
    setNameInput(profile!.username);
    setNameError('');
    setEditing(true);
  }

  function cancelEdit() {
    setEditing(false);
    setNameError('');
  }

  async function saveUsername() {
    const trimmed = nameInput.trim();
    if (!trimmed || trimmed === profile!.username) { cancelEdit(); return; }
    setNameSaving(true);
    setNameError('');
    const err = await updateUsername(user!.id, trimmed);
    setNameSaving(false);
    if (err) { setNameError(err); return; }
    setEditing(false);
  }

  async function handleSignOut() {
    setConfirmSignOut(false);
    showToast(t('auth.signed_out'));
    await signOut();
  }

  async function handleDeleteAccount() {
    setDeleting(true);
    setDeleteError('');
    const err = await deleteAccount();
    if (err) {
      setDeleting(false);
      setDeleteError(err);
    } else {
      showToast(t('account.delete_account_toast'));
    }
  }

  // Detect auto-generated username pattern: AdjectiveNoun#N
  const isAutoGenerated = profile ? /^[A-Z][a-z]+[A-Z][a-z]+#\d+$/.test(profile.username) : false;

  return (
    <div className={`modal-overlay${closing ? ' closing' : ''}`} onPointerDown={handleClose}>
      <div className={`modal-sheet${closing ? ' closing' : ''}`} onPointerDown={e => e.stopPropagation()}>
        <div className="modal-sheet-header">
          <div className="modal-sheet-back" />
          <span className="modal-sheet-title">{t('account.title')}</span>
          <button
            className="btn-utility header-icon-btn modal-sheet-close"
            onClick={handleClose}
            aria-label="Close"
          >
            <img src="/assets/ui/icon-close.svg" className="header-icon-img" alt="" />
          </button>
        </div>

        <div className="modal-sheet-body">

          {!profile ? (
            <span className="scoreboard-loading">{t('common.loading')}</span>
          ) : editing ? (
            <>
              <div className="account-username-row">
                <input
                  className="auth-field account-edit-field"
                  type="text"
                  maxLength={20}
                  value={nameInput}
                  autoFocus
                  onChange={e => { setNameInput(e.target.value); setNameError(''); }}
                  onKeyDown={e => {
                    if (e.key === 'Enter') saveUsername();
                    if (e.key === 'Escape') cancelEdit();
                  }}
                />
                <button className="btn btn-sm" onClick={saveUsername} disabled={nameSaving}>
                  {nameSaving ? '...' : t('common.save')}
                </button>
                <button className="btn btn-sm btn-secondary" onClick={cancelEdit}>
                  {t('common.cancel')}
                </button>
              </div>
              <p className={`auth-error${nameError ? ' visible' : ''}`}>{nameError || ' '}</p>
            </>
          ) : (
            <>
              <div className="account-username-row">
                <span className="account-username">{profile.username}</span>
                <button className="btn-link" onClick={startEdit}>
                  {t('common.edit')}
                </button>
              </div>
              {isAutoGenerated && (
                <p className="account-username-nudge">
                  {t('account.auto_name_nudge')}
                </p>
              )}
            </>
          )}

          <div className="account-divider" />

          <span className="account-section-label">{t('account.campaign_section')}</span>
          <div className="account-stat-row">
            <span>{t('account.clears')}</span>
            <span className="account-stat-value">
              {campaignClearCount > 0 ? campaignClearCount : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>{t('account.best_run')}</span>
            <span className="account-stat-value account-stat-inline">
              {stats ? (
                stats.bestCampaignScore !== null ? (
                  <>
                    {fmt(stats.bestCampaignScore)}
                    <span className={`difficulty-badge ${stats.bestCampaignDifficulty}`}>
                      {t('char_select.' + stats.bestCampaignDifficulty)}
                    </span>
                  </>
                ) : '—'
              ) : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>{t('account.fighters_unlocked')}</span>
            <span className="account-stat-value">
              {unlockedCharacterIds.filter(id => !BASE_UNLOCKED.includes(id)).length}
            </span>
          </div>

          <div className="account-divider" />

          <span className="account-section-label">{t('account.quick_match_section')}</span>
          <div className="account-stat-row">
            <span>{t('account.record')}</span>
            <span className="account-stat-value">
              {stats ? `${stats.rankedWins}W / ${stats.rankedLosses}L` : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>{t('account.win_rate')}</span>
            <span className="account-stat-value">
              {stats ? (stats.winRate !== null ? `${stats.winRate}%` : '—') : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>{t('account.best_streak')}</span>
            <span className="account-stat-value">
              {stats ? (stats.bestWinStreak > 0 ? stats.bestWinStreak : '—') : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>{t('account.matches_played')}</span>
            <span className="account-stat-value">
              {stats ? (stats.matchesQuick > 0 ? stats.matchesQuick : '—') : '—'}
            </span>
          </div>

          {stats && stats.matchesPractice > 0 && (
            <>
              <div className="account-divider" />
              <span className="account-section-label">{t('account.practice_section')}</span>
              <div className="account-stat-row">
                <span>{t('account.matches_played')}</span>
                <span className="account-stat-value">{stats.matchesPractice}</span>
              </div>
            </>
          )}

          <div className="account-divider" />

          <span className="account-section-label">{t('account.delete_section')}</span>
          <p className="account-delete-desc">{t('account.delete_desc')}</p>
          <button className="btn btn-danger btn-sm" onClick={() => setConfirmDelete(true)}>
            {t('account.delete_account')}
          </button>

          <div className="account-divider" />

          <button className="auth-signout-link" onClick={() => setConfirmSignOut(true)}>
            {t('account.sign_out')}
          </button>

        </div>
      </div>

      {confirmSignOut && (
        <div className="confirm-overlay" onPointerDown={e => e.stopPropagation()}>
          <div className="confirm-dialog">
            <span className="dialog-title">{t('account.sign_out_confirm')}</span>
            <div className="confirm-dialog-btns">
              <button className="btn btn-secondary" onClick={() => setConfirmSignOut(false)}>
                {t('common.cancel')}
              </button>
              <button className="btn" onClick={handleSignOut}>
                {t('account.sign_out')}
              </button>
            </div>
          </div>
        </div>
      )}

      {confirmDelete && (
        <div className="confirm-overlay" onPointerDown={e => e.stopPropagation()}>
          <div className="confirm-dialog">
            <span className="dialog-title">{t('account.delete_confirm_title')}</span>
            <p className="confirm-dialog-body">
              {deleteError || t('account.delete_confirm_body')}
            </p>
            <div className="confirm-dialog-btns">
              <button className="btn btn-secondary" onClick={() => { setConfirmDelete(false); setDeleteError(''); }} disabled={deleting}>
                {t('common.cancel')}
              </button>
              <button className="btn btn-danger" onClick={handleDeleteAccount} disabled={deleting}>
                {deleting ? '...' : t('account.delete_confirm_cta')}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
