import { useEffect, useState } from 'react';
import { useAuthStore } from '../../auth/authStore';
import { useGameStore } from '../../store/gameStore';
import { signOut, updateUsername } from '../../auth/authService';
import { loadMyStats, type MyStats } from '../../stats/statsService';
import { BASE_UNLOCKED } from '../../progression/progressionService';
import { useModalAnimation } from '../../hooks/useModalAnimation';
import { showToast } from '../../toasts/toastStore';

function fmt(n: number): string {
  return n.toLocaleString();
}


export default function AccountScreen() {
  const accountOpen = useAuthStore(s => s.accountOpen);
  const closeAll = useAuthStore(s => s.closeAll);
  const profile = useAuthStore(s => s.profile);
  const user = useAuthStore(s => s.user);
  const unlockedCharacterIds = useGameStore(s => s.unlockedCharacterIds);
  const campaignClearCount = useGameStore(s => s.campaignClearCount);

  const { rendered, closing } = useModalAnimation(accountOpen);

  const [confirmSignOut, setConfirmSignOut] = useState(false);

  // Reset confirm dialog whenever the modal closes so re-opening starts clean.
  useEffect(() => {
    if (!accountOpen) setConfirmSignOut(false);
  }, [accountOpen]);
  const [editing, setEditing] = useState(false);
  const [nameInput, setNameInput] = useState('');
  const [nameError, setNameError] = useState('');
  const [nameSaving, setNameSaving] = useState(false);
  const [stats, setStats] = useState<MyStats | null>(null);

  useEffect(() => {
    if (!accountOpen || !user) return;
    setStats(null);
    loadMyStats(user.id).then(setStats);
    // Fallback: if profile didn't load via onAuthStateChange (e.g. silent error on refresh), load it now
    if (!profile) {
      import('../../auth/authService').then(m => m.handleAuthStateChange(user.id));
    }
  }, [accountOpen, user, profile]);

  if (!rendered || !user) return null;

  function handleClose() {
    setEditing(false);
    setNameError('');
    closeAll();
  }

  function startEdit() {
    setNameInput(profile!.username);
    setNameError('');
    setEditing(true);
  }

  function cancelEdit() {
    setEditing(false);
    setNameError('');
  }

  async function saveUsername() {
    const trimmed = nameInput.trim();
    if (!trimmed || trimmed === profile!.username) { cancelEdit(); return; }
    setNameSaving(true);
    setNameError('');
    const err = await updateUsername(user!.id, trimmed);
    setNameSaving(false);
    if (err) { setNameError(err); return; }
    setEditing(false);
  }

  async function handleSignOut() {
    setConfirmSignOut(false);
    showToast('Signed out.');
    await signOut();
  }

  // Detect auto-generated username pattern: AdjectiveNoun#N
  const isAutoGenerated = profile ? /^[A-Z][a-z]+[A-Z][a-z]+#\d+$/.test(profile.username) : false;

  return (
    <div className={`modal-overlay${closing ? ' closing' : ''}`} onPointerDown={handleClose}>
      <div className={`modal-sheet${closing ? ' closing' : ''}`} onPointerDown={e => e.stopPropagation()}>
        <div className="modal-sheet-header">
          <div className="modal-sheet-back" />
          <span className="modal-sheet-title">MY ACCOUNT</span>
          <button
            className="btn-utility header-icon-btn modal-sheet-close"
            onClick={handleClose}
            aria-label="Close"
          >
            <img src="/assets/ui/icon-close.svg" className="header-icon-img" alt="" />
          </button>
        </div>

        <div className="modal-sheet-body">

          {!profile ? (
            <span className="scoreboard-loading">LOADING…</span>
          ) : editing ? (
            <>
              <div className="account-username-row">
                <input
                  className="auth-field account-edit-field"
                  type="text"
                  maxLength={20}
                  value={nameInput}
                  autoFocus
                  onChange={e => { setNameInput(e.target.value); setNameError(''); }}
                  onKeyDown={e => {
                    if (e.key === 'Enter') saveUsername();
                    if (e.key === 'Escape') cancelEdit();
                  }}
                />
                <button className="btn btn-sm" onClick={saveUsername} disabled={nameSaving}>
                  {nameSaving ? '...' : 'SAVE'}
                </button>
                <button className="btn btn-sm btn-secondary" onClick={cancelEdit}>
                  CANCEL
                </button>
              </div>
              <p className={`auth-error${nameError ? ' visible' : ''}`}>{nameError || '\u00A0'}</p>
            </>
          ) : (
            <>
              <div className="account-username-row">
                <span className="account-username">{profile.username}</span>
                <button className="btn-link" onClick={startEdit}>
                  EDIT
                </button>
              </div>
              {isAutoGenerated && (
                <p className="account-username-nudge">
                  This is your auto-generated fighter name. Want to set your own?
                </p>
              )}
            </>
          )}

          <div className="account-divider" />

          <span className="account-section-label">Quick Match</span>
          <div className="account-stat-row">
            <span>Record</span>
            <span className="account-stat-value">
              {stats ? `${stats.rankedWins}W / ${stats.rankedLosses}L` : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>Win rate</span>
            <span className="account-stat-value">
              {stats ? (stats.winRate !== null ? `${stats.winRate}%` : '—') : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>Best streak</span>
            <span className="account-stat-value">
              {stats ? (stats.bestWinStreak > 0 ? stats.bestWinStreak : '—') : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>Matches played</span>
            <span className="account-stat-value">
              {stats ? (stats.matchesQuick > 0 ? stats.matchesQuick : '—') : '—'}
            </span>
          </div>

          <div className="account-divider" />

          <span className="account-section-label">Campaign</span>
          <div className="account-stat-row">
            <span>Clears</span>
            <span className="account-stat-value">
              {campaignClearCount > 0 ? campaignClearCount : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>Best run</span>
            <span className="account-stat-value account-stat-inline">
              {stats ? (
                stats.bestCampaignScore !== null ? (
                  <>
                    {fmt(stats.bestCampaignScore)}
                    <span className={`difficulty-badge ${stats.bestCampaignDifficulty}`}>
                      {stats.bestCampaignDifficulty}
                    </span>
                  </>
                ) : '—'
              ) : '—'}
            </span>
          </div>
          <div className="account-stat-row">
            <span>Matches played</span>
            <span className="account-stat-value">
              {stats ? (stats.matchesCampaign > 0 ? stats.matchesCampaign : '—') : '—'}
            </span>
          </div>

          {stats && stats.matchesPractice > 0 && (
            <>
              <div className="account-divider" />
              <span className="account-section-label">Practice</span>
              <div className="account-stat-row">
                <span>Matches played</span>
                <span className="account-stat-value">{stats.matchesPractice}</span>
              </div>
            </>
          )}

          <div className="account-divider" />

          <span className="account-section-label">Progression</span>
          <div className="account-stat-row">
            <span>Fighters unlocked</span>
            <span className="account-stat-value">
              {unlockedCharacterIds.filter(id => !BASE_UNLOCKED.includes(id)).length}
            </span>
          </div>
          <div className="account-stat-row">
            <span>Campaign clears</span>
            <span className="account-stat-value">
              {campaignClearCount > 0 ? campaignClearCount : '—'}
            </span>
          </div>

          <div className="account-divider" />

          <button className="auth-signout-link" onClick={() => setConfirmSignOut(true)}>
            SIGN OUT
          </button>

        </div>
      </div>

      {confirmSignOut && (
        <div className="confirm-overlay" onPointerDown={e => e.stopPropagation()}>
          <div className="confirm-dialog">
            <span className="dialog-title">SIGN OUT?</span>
            <div className="confirm-dialog-btns">
              <button className="btn btn-secondary" onClick={() => setConfirmSignOut(false)}>
                CANCEL
              </button>
              <button className="btn" onClick={handleSignOut}>
                SIGN OUT
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
